/* Bindings for every symbol the Android library imports.
 *
 * GENERATED by tools/gen_imports.py -- do not edit by hand. Re-run the
 * generator against a game library to refresh it; any symbol it cannot
 * classify is reported instead of silently dropped.
 */

#define _GNU_SOURCE

#include <dirent.h>
#include <errno.h>
#include <locale.h>
#include <malloc.h>
#include <math.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <netinet/in.h>
#include <poll.h>
#include <pthread.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/times.h>
#include <time.h>
#include <unistd.h>
#include <wctype.h>
#include <wchar.h>
#include <zlib.h>

#include <EGL/egl.h>
#include <GLES3/gl3.h>

#include "epoll_shim.h"
#include "errno_shim.h"
#include "gl_shim.h"
#include "imports.h"
#include "io_shim.h"
#include "jni_env.h"
#include "net_shim.h"
#include "opensles.h"
#include "pthread_shim.h"
#include "shims.h"
#include "so_util.h"
#include "sys_shim.h"

/* Bitmap entry points live with the rest of the Java bridge. */
int AndroidBitmap_getInfo(void *env, jobject bitmap, void *info);
int AndroidBitmap_lockPixels(void *env, jobject bitmap, void **pixels);
int AndroidBitmap_unlockPixels(void *env, jobject bitmap);

/* ------------------------------------------------ inert entry points */
/* Facilities the console has no equivalent for. Failing loudly here would
 * abort startup, so each one answers the way an unprivileged Linux process
 * would when the feature is unavailable. */
static long stub_alarm(void) { return 0; }
static long stub_chown(void) { return 0; }
static long stub_closelog(void) { return 0; }
static long stub_eventfd(void) { errno = ENOSYS; return -1; }
static long stub_eventfd_read(void) { errno = ENOSYS; return -1; }
static long stub_eventfd_write(void) { errno = ENOSYS; return -1; }
static long stub_execv(void) { errno = ENOSYS; return -1; }
static long stub_execve(void) { errno = ENOSYS; return -1; }
static long stub_fchdir(void) { errno = ENOSYS; return -1; }
static long stub_fchmod(void) { return 0; }
static long stub_fchmodat(void) { return 0; }
static long stub_fchown(void) { return 0; }
static long stub_fchownat(void) { return 0; }
static long stub_fdatasync(void) { return 0; }
static long stub_fgetxattr(void) { errno = ENOSYS; return -1; }
static long stub_flistxattr(void) { errno = ENOSYS; return -1; }
static long stub_flock(void) { return 0; }
static long stub_fork(void) { errno = ENOSYS; return -1; }
static long stub_forkpty(void) { errno = ENOSYS; return -1; }
static long stub_fremovexattr(void) { errno = ENOSYS; return -1; }
static long stub_fsetxattr(void) { errno = ENOSYS; return -1; }
static long stub_futimens(void) { return 0; }
static long stub_getegid(void) { return 0; }
static long stub_geteuid(void) { return 0; }
static long stub_getgid(void) { return 0; }
static long stub_getgrouplist(void) { errno = ENOSYS; return -1; }
static long stub_getgroups(void) { return 0; }
static long stub_gethostbyaddr_r(void) { errno = ENOSYS; return -1; }
static long stub_gethostbyname_r(void) { errno = ENOSYS; return -1; }
static long stub_getitimer(void) { errno = ENOSYS; return -1; }
static void *stub_getlogin(void) { return NULL; }
static long stub_getpgid(void) { return 0; }
static long stub_getpgrp(void) { return 0; }
static long stub_getppid(void) { return 0; }
static long stub_getpriority(void) { return 0; }
static long stub_getpwnam_r(void) { errno = ENOSYS; return -1; }
static long stub_getpwuid_r(void) { errno = ENOSYS; return -1; }
static long stub_getresgid(void) { return 0; }
static long stub_getresuid(void) { return 0; }
static long stub_getsid(void) { return 0; }
static long stub_getuid(void) { return 0; }
static long stub_getxattr(void) { errno = ENOSYS; return -1; }
static long stub_grantpt(void) { errno = ENOSYS; return -1; }
static long stub_if_freenameindex(void) { return 0; }
static void *stub_if_indextoname(void) { return NULL; }
static void *stub_if_nameindex(void) { return NULL; }
static long stub_if_nametoindex(void) { return 0; }
static long stub_killpg(void) { return 0; }
static long stub_lchown(void) { return 0; }
static long stub_lgetxattr(void) { errno = ENOSYS; return -1; }
static long stub_link(void) { errno = ENOSYS; return -1; }
static long stub_linkat(void) { errno = ENOSYS; return -1; }
static long stub_listxattr(void) { errno = ENOSYS; return -1; }
static long stub_llistxattr(void) { errno = ENOSYS; return -1; }
static long stub_lockf(void) { return 0; }
static long stub_login_tty(void) { errno = ENOSYS; return -1; }
static long stub_lremovexattr(void) { errno = ENOSYS; return -1; }
static long stub_lsetxattr(void) { errno = ENOSYS; return -1; }
static long stub_mkfifo(void) { errno = ENOSYS; return -1; }
static long stub_mkfifoat(void) { errno = ENOSYS; return -1; }
static long stub_mknod(void) { errno = ENOSYS; return -1; }
static long stub_mknodat(void) { errno = ENOSYS; return -1; }
static long stub_mlock(void) { return 0; }
static long stub_nice(void) { return 0; }
static long stub_openlog(void) { return 0; }
static long stub_openpty(void) { errno = ENOSYS; return -1; }
static long stub_pause(void) { errno = ENOSYS; return -1; }
static long stub_posix_fadvise(void) { return 0; }
static long stub_posix_fallocate(void) { return 0; }
static long stub_posix_openpt(void) { errno = ENOSYS; return -1; }
static long stub_ptsname_r(void) { errno = ENOSYS; return -1; }
static long stub_removexattr(void) { errno = ENOSYS; return -1; }
static long stub_sched_get_priority_max(void) { return 0; }
static long stub_sched_get_priority_min(void) { return 0; }
static long stub_sched_getparam(void) { errno = ENOSYS; return -1; }
static long stub_sched_getscheduler(void) { errno = ENOSYS; return -1; }
static long stub_sched_rr_get_interval(void) { errno = ENOSYS; return -1; }
static long stub_sched_setparam(void) { errno = ENOSYS; return -1; }
static long stub_sched_setscheduler(void) { errno = ENOSYS; return -1; }
static long stub_sendfile(void) { errno = ENOSYS; return -1; }
static long stub_setgroups(void) { return 0; }
static long stub_setitimer(void) { errno = ENOSYS; return -1; }
static long stub_setns(void) { errno = ENOSYS; return -1; }
static long stub_setpgid(void) { return 0; }
static long stub_setpgrp(void) { return 0; }
static long stub_setpriority(void) { return 0; }
static long stub_setsid(void) { return 0; }
static long stub_setxattr(void) { errno = ENOSYS; return -1; }
static long stub_sigaction(void) { return 0; }
static long stub_sigaddset(void) { return 0; }
static long stub_sigaltstack(void) { return 0; }
static long stub_sigdelset(void) { return 0; }
static long stub_sigemptyset(void) { return 0; }
static long stub_sigfillset(void) { return 0; }
static long stub_sigismember(void) { return 0; }
static long stub_sigpending(void) { return 0; }
static long stub_sigprocmask(void) { return 0; }
static long stub_sigtimedwait(void) { errno = ENOSYS; return -1; }
static long stub_sigwait(void) { errno = ENOSYS; return -1; }
static long stub_sigwaitinfo(void) { errno = ENOSYS; return -1; }
static long stub_splice(void) { errno = ENOSYS; return -1; }
static long stub_symlink(void) { errno = ENOSYS; return -1; }
static long stub_symlinkat(void) { errno = ENOSYS; return -1; }
static long stub_sync(void) { return 0; }
static long stub_syslog(void) { return 0; }
static long stub_system(void) { errno = ENOSYS; return -1; }
static long stub_tcgetpgrp(void) { errno = ENOSYS; return -1; }
static long stub_tcsetpgrp(void) { errno = ENOSYS; return -1; }
static long stub_timerfd_create(void) { errno = ENOSYS; return -1; }
static long stub_timerfd_gettime(void) { errno = ENOSYS; return -1; }
static long stub_timerfd_settime(void) { errno = ENOSYS; return -1; }
static long stub_ttyname_r(void) { errno = ENOSYS; return -1; }
static long stub_umask(void) { return 0; }
static long stub_unlockpt(void) { errno = ENOSYS; return -1; }
static long stub_unshare(void) { errno = ENOSYS; return -1; }
static long stub_utimensat(void) { return 0; }
static long stub_utimes(void) { return 0; }
static long stub_vfork(void) { errno = ENOSYS; return -1; }
static long stub_wait(void) { errno = ENOSYS; return -1; }
static long stub_wait4(void) { errno = ENOSYS; return -1; }
static long stub_waitid(void) { errno = ENOSYS; return -1; }
static long stub_waitpid(void) { errno = ENOSYS; return -1; }

/* --------------------------------------------------------- the table */

DynLibFunction dynlib_functions[] = {
    {"AndroidBitmap_getInfo", (uintptr_t)&AndroidBitmap_getInfo},
    {"AndroidBitmap_lockPixels", (uintptr_t)&AndroidBitmap_lockPixels},
    {"AndroidBitmap_unlockPixels", (uintptr_t)&AndroidBitmap_unlockPixels},
    {"__FD_ISSET_chk", (uintptr_t)&shim_fd_isset_chk},
    {"__FD_SET_chk", (uintptr_t)&shim_fd_set_chk},
    {"__android_log_print", (uintptr_t)&bionic_android_log_print},
    {"__android_log_write", (uintptr_t)&bionic_android_log_write},
    {"__assert2", (uintptr_t)&bionic_assert2},
    {"__cmsg_nxthdr", (uintptr_t)&shim_cmsg_nxthdr},
    {"__ctype_get_mb_cur_max", (uintptr_t)&shim_ctype_get_mb_cur_max},
    {"__cxa_atexit", (uintptr_t)&shim_cxa_atexit},
    {"__cxa_finalize", (uintptr_t)&shim_cxa_finalize},
    {"__cxa_thread_atexit_impl", (uintptr_t)&shim_cxa_thread_atexit},
    {"__errno", (uintptr_t)&bionic_errno_location},
    {"__get_h_errno", (uintptr_t)&bionic_h_errno_location},
    {"__gnu_strerror_r", (uintptr_t)&shim_gnu_strerror_r},
    {"__libc_current_sigrtmax", (uintptr_t)&shim_sigrtmax},
    {"__libc_current_sigrtmin", (uintptr_t)&shim_sigrtmin},
    {"__memcpy_chk", (uintptr_t)&shim_memcpy_chk},
    {"__poll_chk", (uintptr_t)&shim_poll_chk},
    {"__read_chk", (uintptr_t)&shim_read_chk},
    {"__register_atfork", (uintptr_t)&shim_register_atfork},
    {"__sF", (uintptr_t)&bionic_sF},
    {"__sched_cpualloc", (uintptr_t)&shim_sched_cpualloc},
    {"__sched_cpucount", (uintptr_t)&shim_sched_cpucount},
    {"__sched_cpufree", (uintptr_t)&shim_sched_cpufree},
    {"__stack_chk_fail", (uintptr_t)&bionic_stack_chk_fail},
    {"__strchr_chk", (uintptr_t)&shim_strchr_chk},
    {"__strcpy_chk", (uintptr_t)&shim_strcpy_chk},
    {"__strlen_chk", (uintptr_t)&shim_strlen_chk},
    {"__strncpy_chk", (uintptr_t)&shim_strncpy_chk},
    {"__system_property_get", (uintptr_t)&bionic_system_property_get},
    {"__vsnprintf_chk", (uintptr_t)&shim_vsnprintf_chk},
    {"__vsprintf_chk", (uintptr_t)&shim_vsprintf_chk},
    {"__write_chk", (uintptr_t)&shim_write_chk},
    {"_exit", (uintptr_t)&_exit},
    {"abort", (uintptr_t)&bionic_abort},
    {"accept", (uintptr_t)&net_accept},
    {"accept4", (uintptr_t)&net_accept4},
    {"access", (uintptr_t)&bionic_access},
    {"acos", (uintptr_t)&acos},
    {"acosf", (uintptr_t)&acosf},
    {"acosh", (uintptr_t)&acosh},
    {"adler32", (uintptr_t)&adler32},
    {"alarm", (uintptr_t)&stub_alarm},
    {"android_set_abort_message", (uintptr_t)&bionic_set_abort_message},
    {"arc4random_buf", (uintptr_t)&bionic_arc4random_buf},
    {"asin", (uintptr_t)&asin},
    {"asinf", (uintptr_t)&asinf},
    {"asinh", (uintptr_t)&asinh},
    {"atan", (uintptr_t)&atan},
    {"atan2", (uintptr_t)&atan2},
    {"atan2f", (uintptr_t)&atan2f},
    {"atanf", (uintptr_t)&atanf},
    {"atanh", (uintptr_t)&atanh},
    {"atoi", (uintptr_t)&atoi},
    {"basename", (uintptr_t)&shim_basename},
    {"bind", (uintptr_t)&net_bind},
    {"btowc", (uintptr_t)&btowc},
    {"calloc", (uintptr_t)&calloc},
    {"cbrt", (uintptr_t)&cbrt},
    {"cbrtf", (uintptr_t)&cbrtf},
    {"chdir", (uintptr_t)&bionic_chdir},
    {"chmod", (uintptr_t)&bionic_chmod},
    {"chown", (uintptr_t)&stub_chown},
    {"clearerr", (uintptr_t)&shim_clearerr},
    {"clock", (uintptr_t)&clock},
    {"clock_getres", (uintptr_t)&shim_clock_getres},
    {"clock_gettime", (uintptr_t)&shim_clock_gettime},
    {"clock_nanosleep", (uintptr_t)&shim_clock_nanosleep},
    {"close", (uintptr_t)&bionic_close},
    {"closedir", (uintptr_t)&bionic_closedir},
    {"closelog", (uintptr_t)&stub_closelog},
    {"connect", (uintptr_t)&net_connect},
    {"copysign", (uintptr_t)&copysign},
    {"cos", (uintptr_t)&cos},
    {"cosf", (uintptr_t)&cosf},
    {"cosh", (uintptr_t)&cosh},
    {"crc32", (uintptr_t)&crc32},
    {"deflate", (uintptr_t)&deflate},
    {"deflateCopy", (uintptr_t)&deflateCopy},
    {"deflateEnd", (uintptr_t)&deflateEnd},
    {"deflateInit2_", (uintptr_t)&deflateInit2_},
    {"deflateSetDictionary", (uintptr_t)&deflateSetDictionary},
    {"dl_iterate_phdr", (uintptr_t)&so_dl_iterate_phdr},
    {"dladdr", (uintptr_t)&shim_dladdr},
    {"dlclose", (uintptr_t)&shim_dlclose},
    {"dlerror", (uintptr_t)&shim_dlerror},
    {"dlopen", (uintptr_t)&shim_dlopen},
    {"dlsym", (uintptr_t)&shim_dlsym},
    {"dprintf", (uintptr_t)&shim_dprintf},
    {"dup", (uintptr_t)&bionic_dup},
    {"dup2", (uintptr_t)&bionic_dup2},
    {"dup3", (uintptr_t)&net_dup3},
    {"eglGetProcAddress", (uintptr_t)&gl_shim_eglGetProcAddress},
    {"environ", (uintptr_t)&bionic_environ},
    {"epoll_create1", (uintptr_t)&shim_epoll_create1},
    {"epoll_ctl", (uintptr_t)&shim_epoll_ctl},
    {"epoll_wait", (uintptr_t)&shim_epoll_wait},
    {"erf", (uintptr_t)&erf},
    {"erfc", (uintptr_t)&erfc},
    {"eventfd", (uintptr_t)&stub_eventfd},
    {"eventfd_read", (uintptr_t)&stub_eventfd_read},
    {"eventfd_write", (uintptr_t)&stub_eventfd_write},
    {"execv", (uintptr_t)&stub_execv},
    {"execve", (uintptr_t)&stub_execve},
    {"exit", (uintptr_t)&exit},
    {"exp", (uintptr_t)&exp},
    {"exp2", (uintptr_t)&exp2},
    {"exp2f", (uintptr_t)&exp2f},
    {"expf", (uintptr_t)&expf},
    {"expm1", (uintptr_t)&expm1},
    {"fabs", (uintptr_t)&fabs},
    {"fchdir", (uintptr_t)&stub_fchdir},
    {"fchmod", (uintptr_t)&stub_fchmod},
    {"fchmodat", (uintptr_t)&stub_fchmodat},
    {"fchown", (uintptr_t)&stub_fchown},
    {"fchownat", (uintptr_t)&stub_fchownat},
    {"fclose", (uintptr_t)&shim_fclose},
    {"fcntl", (uintptr_t)&bionic_fcntl},
    {"fdatasync", (uintptr_t)&stub_fdatasync},
    {"fdopen", (uintptr_t)&bionic_fdopen},
    {"fdopendir", (uintptr_t)&bionic_fdopendir},
    {"feof", (uintptr_t)&shim_feof},
    {"ferror", (uintptr_t)&shim_ferror},
    {"fflush", (uintptr_t)&shim_fflush},
    {"fgetc", (uintptr_t)&shim_fgetc},
    {"fgets", (uintptr_t)&shim_fgets},
    {"fgetxattr", (uintptr_t)&stub_fgetxattr},
    {"fileno", (uintptr_t)&shim_fileno},
    {"flistxattr", (uintptr_t)&stub_flistxattr},
    {"flock", (uintptr_t)&stub_flock},
    {"flockfile", (uintptr_t)&shim_flockfile},
    {"fmod", (uintptr_t)&fmod},
    {"fmodf", (uintptr_t)&fmodf},
    {"fopen", (uintptr_t)&bionic_fopen},
    {"fork", (uintptr_t)&stub_fork},
    {"forkpty", (uintptr_t)&stub_forkpty},
    {"fpathconf", (uintptr_t)&shim_pathconf_fd},
    {"fprintf", (uintptr_t)&shim_fprintf},
    {"fputc", (uintptr_t)&shim_fputc},
    {"fputs", (uintptr_t)&shim_fputs},
    {"fputwc", (uintptr_t)&shim_fputwc},
    {"fread", (uintptr_t)&shim_fread},
    {"free", (uintptr_t)&free},
    {"freeaddrinfo", (uintptr_t)&net_freeaddrinfo},
    {"freelocale", (uintptr_t)&bionic_freelocale},
    {"fremovexattr", (uintptr_t)&stub_fremovexattr},
    {"frexp", (uintptr_t)&frexp},
    {"frexpf", (uintptr_t)&frexpf},
    {"fscanf", (uintptr_t)&shim_fscanf},
    {"fseek", (uintptr_t)&shim_fseek},
    {"fseeko", (uintptr_t)&shim_fseeko},
    {"fsetxattr", (uintptr_t)&stub_fsetxattr},
    {"fstat", (uintptr_t)&bionic_fstat},
    {"fstatat", (uintptr_t)&bionic_fstatat},
    {"fstatvfs", (uintptr_t)&bionic_fstatvfs},
    {"fsync", (uintptr_t)&bionic_fsync},
    {"ftell", (uintptr_t)&shim_ftell},
    {"ftello", (uintptr_t)&shim_ftello},
    {"ftruncate", (uintptr_t)&bionic_ftruncate},
    {"funlockfile", (uintptr_t)&shim_funlockfile},
    {"futimens", (uintptr_t)&stub_futimens},
    {"fwrite", (uintptr_t)&shim_fwrite},
    {"gai_strerror", (uintptr_t)&gai_strerror},
    {"getaddrinfo", (uintptr_t)&net_getaddrinfo},
    {"getauxval", (uintptr_t)&bionic_getauxval},
    {"getc", (uintptr_t)&shim_getc},
    {"getc_unlocked", (uintptr_t)&shim_getc},
    {"getcwd", (uintptr_t)&bionic_getcwd},
    {"getegid", (uintptr_t)&stub_getegid},
    {"getentropy", (uintptr_t)&bionic_getentropy},
    {"getenv", (uintptr_t)&bionic_getenv},
    {"geteuid", (uintptr_t)&stub_geteuid},
    {"getgid", (uintptr_t)&stub_getgid},
    {"getgrouplist", (uintptr_t)&stub_getgrouplist},
    {"getgroups", (uintptr_t)&stub_getgroups},
    {"gethostbyaddr_r", (uintptr_t)&stub_gethostbyaddr_r},
    {"gethostbyname", (uintptr_t)&net_gethostbyname},
    {"gethostbyname_r", (uintptr_t)&stub_gethostbyname_r},
    {"gethostname", (uintptr_t)&gethostname},
    {"getitimer", (uintptr_t)&stub_getitimer},
    {"getlogin", (uintptr_t)&stub_getlogin},
    {"getnameinfo", (uintptr_t)&net_getnameinfo},
    {"getpeername", (uintptr_t)&net_getpeername},
    {"getpgid", (uintptr_t)&stub_getpgid},
    {"getpgrp", (uintptr_t)&stub_getpgrp},
    {"getpid", (uintptr_t)&shim_getpid},
    {"getppid", (uintptr_t)&stub_getppid},
    {"getpriority", (uintptr_t)&stub_getpriority},
    {"getprotobyname", (uintptr_t)&getprotobyname},
    {"getpwnam_r", (uintptr_t)&stub_getpwnam_r},
    {"getpwuid_r", (uintptr_t)&stub_getpwuid_r},
    {"getresgid", (uintptr_t)&stub_getresgid},
    {"getresuid", (uintptr_t)&stub_getresuid},
    {"getrlimit", (uintptr_t)&shim_getrlimit},
    {"getrusage", (uintptr_t)&shim_getrusage},
    {"getservbyname", (uintptr_t)&getservbyname},
    {"getservbyport", (uintptr_t)&getservbyport},
    {"getsid", (uintptr_t)&stub_getsid},
    {"getsockname", (uintptr_t)&net_getsockname},
    {"getsockopt", (uintptr_t)&net_getsockopt},
    {"gettid", (uintptr_t)&bionic_gettid},
    {"gettimeofday", (uintptr_t)&gettimeofday},
    {"getuid", (uintptr_t)&stub_getuid},
    {"getwc", (uintptr_t)&shim_getwc},
    {"getxattr", (uintptr_t)&stub_getxattr},
    {"glActiveTexture", (uintptr_t)&glActiveTexture},
    {"glAttachShader", (uintptr_t)&glAttachShader},
    {"glBindAttribLocation", (uintptr_t)&glBindAttribLocation},
    {"glBindBuffer", (uintptr_t)&glBindBuffer},
    {"glBindFramebuffer", (uintptr_t)&glBindFramebuffer},
    {"glBindRenderbuffer", (uintptr_t)&glBindRenderbuffer},
    {"glBindTexture", (uintptr_t)&glBindTexture},
    {"glBindVertexArray", (uintptr_t)&glBindVertexArray},
    {"glBlendFunc", (uintptr_t)&glBlendFunc},
    {"glBlendFuncSeparate", (uintptr_t)&glBlendFuncSeparate},
    {"glBlitFramebuffer", (uintptr_t)&glBlitFramebuffer},
    {"glBufferData", (uintptr_t)&glBufferData},
    {"glCheckFramebufferStatus", (uintptr_t)&glCheckFramebufferStatus},
    {"glClear", (uintptr_t)&glClear},
    {"glClearColor", (uintptr_t)&glClearColor},
    {"glCompileShader", (uintptr_t)&glCompileShader},
    {"glCompressedTexImage2D", (uintptr_t)&gl_shim_CompressedTexImage2D},
    {"glCreateProgram", (uintptr_t)&glCreateProgram},
    {"glCreateShader", (uintptr_t)&glCreateShader},
    {"glCullFace", (uintptr_t)&glCullFace},
    {"glDeleteBuffers", (uintptr_t)&glDeleteBuffers},
    {"glDeleteFramebuffers", (uintptr_t)&glDeleteFramebuffers},
    {"glDeleteProgram", (uintptr_t)&glDeleteProgram},
    {"glDeleteRenderbuffers", (uintptr_t)&glDeleteRenderbuffers},
    {"glDeleteShader", (uintptr_t)&glDeleteShader},
    {"glDeleteTextures", (uintptr_t)&glDeleteTextures},
    {"glDeleteVertexArrays", (uintptr_t)&glDeleteVertexArrays},
    {"glDepthFunc", (uintptr_t)&glDepthFunc},
    {"glDepthMask", (uintptr_t)&glDepthMask},
    {"glDepthRangef", (uintptr_t)&glDepthRangef},
    {"glDetachShader", (uintptr_t)&glDetachShader},
    {"glDisable", (uintptr_t)&glDisable},
    {"glDrawArrays", (uintptr_t)&glDrawArrays},
    {"glDrawElements", (uintptr_t)&glDrawElements},
    {"glEnable", (uintptr_t)&glEnable},
    {"glEnableVertexAttribArray", (uintptr_t)&glEnableVertexAttribArray},
    {"glFramebufferRenderbuffer", (uintptr_t)&glFramebufferRenderbuffer},
    {"glFramebufferTexture2D", (uintptr_t)&glFramebufferTexture2D},
    {"glGenBuffers", (uintptr_t)&glGenBuffers},
    {"glGenFramebuffers", (uintptr_t)&glGenFramebuffers},
    {"glGenRenderbuffers", (uintptr_t)&glGenRenderbuffers},
    {"glGenTextures", (uintptr_t)&glGenTextures},
    {"glGenVertexArrays", (uintptr_t)&glGenVertexArrays},
    {"glGenerateMipmap", (uintptr_t)&glGenerateMipmap},
    {"glGetError", (uintptr_t)&glGetError},
    {"glGetFloatv", (uintptr_t)&glGetFloatv},
    {"glGetIntegerv", (uintptr_t)&glGetIntegerv},
    {"glGetInternalformativ", (uintptr_t)&glGetInternalformativ},
    {"glGetProgramInfoLog", (uintptr_t)&glGetProgramInfoLog},
    {"glGetProgramiv", (uintptr_t)&glGetProgramiv},
    {"glGetShaderInfoLog", (uintptr_t)&glGetShaderInfoLog},
    {"glGetShaderiv", (uintptr_t)&glGetShaderiv},
    {"glGetString", (uintptr_t)&glGetString},
    {"glGetStringi", (uintptr_t)&glGetStringi},
    {"glGetUniformLocation", (uintptr_t)&glGetUniformLocation},
    {"glInvalidateFramebuffer", (uintptr_t)&glInvalidateFramebuffer},
    {"glLinkProgram", (uintptr_t)&glLinkProgram},
    {"glReadPixels", (uintptr_t)&glReadPixels},
    {"glRenderbufferStorage", (uintptr_t)&glRenderbufferStorage},
    {"glRenderbufferStorageMultisample", (uintptr_t)&glRenderbufferStorageMultisample},
    {"glScissor", (uintptr_t)&glScissor},
    {"glShaderSource", (uintptr_t)&glShaderSource},
    {"glTexImage2D", (uintptr_t)&glTexImage2D},
    {"glTexParameterf", (uintptr_t)&glTexParameterf},
    {"glTexParameteri", (uintptr_t)&glTexParameteri},
    {"glUniform1f", (uintptr_t)&glUniform1f},
    {"glUniform1fv", (uintptr_t)&glUniform1fv},
    {"glUniform1i", (uintptr_t)&glUniform1i},
    {"glUniform2f", (uintptr_t)&glUniform2f},
    {"glUniform4f", (uintptr_t)&glUniform4f},
    {"glUniformMatrix4fv", (uintptr_t)&glUniformMatrix4fv},
    {"glUseProgram", (uintptr_t)&glUseProgram},
    {"glVertexAttribPointer", (uintptr_t)&glVertexAttribPointer},
    {"glViewport", (uintptr_t)&glViewport},
    {"gmtime_r", (uintptr_t)&shim_gmtime_r},
    {"grantpt", (uintptr_t)&stub_grantpt},
    {"hstrerror", (uintptr_t)&hstrerror},
    {"hypot", (uintptr_t)&hypot},
    {"hypotf", (uintptr_t)&hypotf},
    {"if_freenameindex", (uintptr_t)&stub_if_freenameindex},
    {"if_indextoname", (uintptr_t)&stub_if_indextoname},
    {"if_nameindex", (uintptr_t)&stub_if_nameindex},
    {"if_nametoindex", (uintptr_t)&stub_if_nametoindex},
    {"in6addr_any", (uintptr_t)&in6addr_any},
    {"in6addr_loopback", (uintptr_t)&in6addr_loopback},
    {"inet_aton", (uintptr_t)&inet_aton},
    {"inet_ntoa", (uintptr_t)&inet_ntoa},
    {"inet_ntop", (uintptr_t)&net_inet_ntop},
    {"inet_pton", (uintptr_t)&net_inet_pton},
    {"inflate", (uintptr_t)&inflate},
    {"inflateCopy", (uintptr_t)&inflateCopy},
    {"inflateEnd", (uintptr_t)&inflateEnd},
    {"inflateInit2_", (uintptr_t)&inflateInit2_},
    {"inflateSetDictionary", (uintptr_t)&inflateSetDictionary},
    {"ioctl", (uintptr_t)&bionic_ioctl},
    {"isatty", (uintptr_t)&bionic_isatty},
    {"iswalpha_l", (uintptr_t)&shim_iswalpha_l},
    {"iswblank_l", (uintptr_t)&shim_iswblank_l},
    {"iswcntrl_l", (uintptr_t)&shim_iswcntrl_l},
    {"iswdigit_l", (uintptr_t)&shim_iswdigit_l},
    {"iswlower_l", (uintptr_t)&shim_iswlower_l},
    {"iswprint_l", (uintptr_t)&shim_iswprint_l},
    {"iswpunct_l", (uintptr_t)&shim_iswpunct_l},
    {"iswspace_l", (uintptr_t)&shim_iswspace_l},
    {"iswupper_l", (uintptr_t)&shim_iswupper_l},
    {"iswxdigit_l", (uintptr_t)&shim_iswxdigit_l},
    {"kill", (uintptr_t)&kill},
    {"killpg", (uintptr_t)&stub_killpg},
    {"lchown", (uintptr_t)&stub_lchown},
    {"ldexp", (uintptr_t)&ldexp},
    {"ldexpf", (uintptr_t)&ldexpf},
    {"lgetxattr", (uintptr_t)&stub_lgetxattr},
    {"link", (uintptr_t)&stub_link},
    {"linkat", (uintptr_t)&stub_linkat},
    {"listen", (uintptr_t)&listen},
    {"listxattr", (uintptr_t)&stub_listxattr},
    {"llistxattr", (uintptr_t)&stub_llistxattr},
    {"localeconv", (uintptr_t)&shim_localeconv},
    {"localtime", (uintptr_t)&shim_localtime},
    {"localtime_r", (uintptr_t)&shim_localtime_r},
    {"lockf", (uintptr_t)&stub_lockf},
    {"log", (uintptr_t)&log},
    {"log10", (uintptr_t)&log10},
    {"log10f", (uintptr_t)&log10f},
    {"log1p", (uintptr_t)&log1p},
    {"log2", (uintptr_t)&log2},
    {"log2f", (uintptr_t)&log2f},
    {"logf", (uintptr_t)&logf},
    {"login_tty", (uintptr_t)&stub_login_tty},
    {"lremovexattr", (uintptr_t)&stub_lremovexattr},
    {"lseek", (uintptr_t)&bionic_lseek},
    {"lsetxattr", (uintptr_t)&stub_lsetxattr},
    {"lstat", (uintptr_t)&bionic_lstat},
    {"madvise", (uintptr_t)&bionic_madvise},
    {"malloc", (uintptr_t)&malloc},
    {"mbrlen", (uintptr_t)&mbrlen},
    {"mbrtowc", (uintptr_t)&mbrtowc},
    {"mbsnrtowcs", (uintptr_t)&mbsnrtowcs},
    {"mbsrtowcs", (uintptr_t)&mbsrtowcs},
    {"mbtowc", (uintptr_t)&mbtowc},
    {"memchr", (uintptr_t)&memchr},
    {"memcmp", (uintptr_t)&memcmp},
    {"memcpy", (uintptr_t)&memcpy},
    {"memmove", (uintptr_t)&memmove},
    {"memrchr", (uintptr_t)&memrchr},
    {"memset", (uintptr_t)&memset},
    {"mkdir", (uintptr_t)&bionic_mkdir},
    {"mkdirat", (uintptr_t)&bionic_mkdirat},
    {"mkfifo", (uintptr_t)&stub_mkfifo},
    {"mkfifoat", (uintptr_t)&stub_mkfifoat},
    {"mknod", (uintptr_t)&stub_mknod},
    {"mknodat", (uintptr_t)&stub_mknodat},
    {"mkstemp", (uintptr_t)&mkstemp},
    {"mktime", (uintptr_t)&shim_mktime},
    {"mlock", (uintptr_t)&stub_mlock},
    {"mmap", (uintptr_t)&bionic_mmap},
    {"modf", (uintptr_t)&modf},
    {"mprotect", (uintptr_t)&bionic_mprotect},
    {"mremap", (uintptr_t)&bionic_mremap},
    {"msync", (uintptr_t)&bionic_msync},
    {"munmap", (uintptr_t)&bionic_munmap},
    {"nanosleep", (uintptr_t)&nanosleep},
    {"newlocale", (uintptr_t)&bionic_newlocale},
    {"nextafter", (uintptr_t)&nextafter},
    {"nice", (uintptr_t)&stub_nice},
    {"open", (uintptr_t)&bionic_open},
    {"openat", (uintptr_t)&bionic_openat},
    {"opendir", (uintptr_t)&bionic_opendir},
    {"openlog", (uintptr_t)&stub_openlog},
    {"openpty", (uintptr_t)&stub_openpty},
    {"pathconf", (uintptr_t)&shim_pathconf},
    {"pause", (uintptr_t)&stub_pause},
    {"perror", (uintptr_t)&shim_perror},
    {"pipe", (uintptr_t)&net_pipe},
    {"pipe2", (uintptr_t)&net_pipe2},
    {"poll", (uintptr_t)&net_poll},
    {"posix_fadvise", (uintptr_t)&stub_posix_fadvise},
    {"posix_fallocate", (uintptr_t)&stub_posix_fallocate},
    {"posix_memalign", (uintptr_t)&shim_posix_memalign},
    {"posix_openpt", (uintptr_t)&stub_posix_openpt},
    {"pow", (uintptr_t)&pow},
    {"powf", (uintptr_t)&powf},
    {"pread", (uintptr_t)&bionic_pread},
    {"preadv", (uintptr_t)&shim_preadv},
    {"printf", (uintptr_t)&shim_printf},
    {"pthread_attr_destroy", (uintptr_t)&bionic_pthread_attr_destroy},
    {"pthread_attr_init", (uintptr_t)&bionic_pthread_attr_init},
    {"pthread_attr_setstacksize", (uintptr_t)&bionic_pthread_attr_setstacksize},
    {"pthread_cond_broadcast", (uintptr_t)&bionic_pthread_cond_broadcast},
    {"pthread_cond_destroy", (uintptr_t)&bionic_pthread_cond_destroy},
    {"pthread_cond_init", (uintptr_t)&bionic_pthread_cond_init},
    {"pthread_cond_signal", (uintptr_t)&bionic_pthread_cond_signal},
    {"pthread_cond_timedwait", (uintptr_t)&bionic_pthread_cond_timedwait},
    {"pthread_cond_wait", (uintptr_t)&bionic_pthread_cond_wait},
    {"pthread_condattr_init", (uintptr_t)&bionic_pthread_condattr_init},
    {"pthread_condattr_setclock", (uintptr_t)&bionic_pthread_condattr_setclock},
    {"pthread_create", (uintptr_t)&bionic_pthread_create},
    {"pthread_detach", (uintptr_t)&bionic_pthread_detach},
    {"pthread_equal", (uintptr_t)&pthread_equal},
    {"pthread_exit", (uintptr_t)&pthread_exit},
    {"pthread_getcpuclockid", (uintptr_t)&bionic_pthread_getcpuclockid},
    {"pthread_getspecific", (uintptr_t)&bionic_pthread_getspecific},
    {"pthread_join", (uintptr_t)&bionic_pthread_join},
    {"pthread_key_create", (uintptr_t)&bionic_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)&bionic_pthread_key_delete},
    {"pthread_kill", (uintptr_t)&bionic_pthread_kill},
    {"pthread_mutex_destroy", (uintptr_t)&bionic_pthread_mutex_destroy},
    {"pthread_mutex_init", (uintptr_t)&bionic_pthread_mutex_init},
    {"pthread_mutex_lock", (uintptr_t)&bionic_pthread_mutex_lock},
    {"pthread_mutex_trylock", (uintptr_t)&bionic_pthread_mutex_trylock},
    {"pthread_mutex_unlock", (uintptr_t)&bionic_pthread_mutex_unlock},
    {"pthread_mutexattr_destroy", (uintptr_t)&bionic_pthread_mutexattr_destroy},
    {"pthread_mutexattr_init", (uintptr_t)&bionic_pthread_mutexattr_init},
    {"pthread_mutexattr_settype", (uintptr_t)&bionic_pthread_mutexattr_settype},
    {"pthread_once", (uintptr_t)&bionic_pthread_once},
    {"pthread_rwlock_destroy", (uintptr_t)&bionic_pthread_rwlock_destroy},
    {"pthread_rwlock_init", (uintptr_t)&bionic_pthread_rwlock_init},
    {"pthread_rwlock_rdlock", (uintptr_t)&bionic_pthread_rwlock_rdlock},
    {"pthread_rwlock_unlock", (uintptr_t)&bionic_pthread_rwlock_unlock},
    {"pthread_rwlock_wrlock", (uintptr_t)&bionic_pthread_rwlock_wrlock},
    {"pthread_self", (uintptr_t)&pthread_self},
    {"pthread_setname_np", (uintptr_t)&bionic_pthread_setname_np},
    {"pthread_setschedparam", (uintptr_t)&bionic_pthread_setschedparam},
    {"pthread_setspecific", (uintptr_t)&bionic_pthread_setspecific},
    {"pthread_sigmask", (uintptr_t)&bionic_pthread_sigmask},
    {"ptsname_r", (uintptr_t)&stub_ptsname_r},
    {"putchar", (uintptr_t)&shim_putchar},
    {"puts", (uintptr_t)&shim_puts},
    {"pwrite", (uintptr_t)&bionic_pwrite},
    {"pwritev", (uintptr_t)&shim_pwritev},
    {"qsort", (uintptr_t)&qsort},
    {"raise", (uintptr_t)&raise},
    {"rand", (uintptr_t)&rand},
    {"read", (uintptr_t)&bionic_read},
    {"readdir", (uintptr_t)&bionic_readdir},
    {"readlink", (uintptr_t)&bionic_readlink},
    {"readlinkat", (uintptr_t)&bionic_readlinkat},
    {"readv", (uintptr_t)&shim_readv},
    {"realloc", (uintptr_t)&realloc},
    {"realpath", (uintptr_t)&bionic_realpath},
    {"recv", (uintptr_t)&net_recv},
    {"recvfrom", (uintptr_t)&net_recvfrom},
    {"recvmsg", (uintptr_t)&net_recvmsg},
    {"remove", (uintptr_t)&bionic_remove},
    {"removexattr", (uintptr_t)&stub_removexattr},
    {"rename", (uintptr_t)&bionic_rename},
    {"renameat", (uintptr_t)&bionic_renameat},
    {"rewind", (uintptr_t)&shim_rewind},
    {"rewinddir", (uintptr_t)&bionic_rewinddir},
    {"rmdir", (uintptr_t)&bionic_rmdir},
    {"sched_get_priority_max", (uintptr_t)&stub_sched_get_priority_max},
    {"sched_get_priority_min", (uintptr_t)&stub_sched_get_priority_min},
    {"sched_getaffinity", (uintptr_t)&shim_sched_getaffinity},
    {"sched_getparam", (uintptr_t)&stub_sched_getparam},
    {"sched_getscheduler", (uintptr_t)&stub_sched_getscheduler},
    {"sched_rr_get_interval", (uintptr_t)&stub_sched_rr_get_interval},
    {"sched_setaffinity", (uintptr_t)&shim_sched_setaffinity},
    {"sched_setparam", (uintptr_t)&stub_sched_setparam},
    {"sched_setscheduler", (uintptr_t)&stub_sched_setscheduler},
    {"sched_yield", (uintptr_t)&shim_sched_yield},
    {"select", (uintptr_t)&net_select},
    {"sem_destroy", (uintptr_t)&bionic_sem_destroy},
    {"sem_init", (uintptr_t)&bionic_sem_init},
    {"sem_post", (uintptr_t)&bionic_sem_post},
    {"sem_timedwait", (uintptr_t)&bionic_sem_timedwait},
    {"sem_trywait", (uintptr_t)&bionic_sem_trywait},
    {"sem_wait", (uintptr_t)&bionic_sem_wait},
    {"send", (uintptr_t)&net_send},
    {"sendfile", (uintptr_t)&stub_sendfile},
    {"sendmsg", (uintptr_t)&net_sendmsg},
    {"sendto", (uintptr_t)&net_sendto},
    {"setbuf", (uintptr_t)&shim_setbuf},
    {"setenv", (uintptr_t)&bionic_setenv},
    {"setgroups", (uintptr_t)&stub_setgroups},
    {"setitimer", (uintptr_t)&stub_setitimer},
    {"setlocale", (uintptr_t)&setlocale},
    {"setns", (uintptr_t)&stub_setns},
    {"setpgid", (uintptr_t)&stub_setpgid},
    {"setpgrp", (uintptr_t)&stub_setpgrp},
    {"setpriority", (uintptr_t)&stub_setpriority},
    {"setrlimit", (uintptr_t)&shim_setrlimit},
    {"setsid", (uintptr_t)&stub_setsid},
    {"setsockopt", (uintptr_t)&net_setsockopt},
    {"setvbuf", (uintptr_t)&shim_setvbuf},
    {"setxattr", (uintptr_t)&stub_setxattr},
    {"shutdown", (uintptr_t)&shutdown},
    {"sigaction", (uintptr_t)&stub_sigaction},
    {"sigaddset", (uintptr_t)&stub_sigaddset},
    {"sigaltstack", (uintptr_t)&stub_sigaltstack},
    {"sigdelset", (uintptr_t)&stub_sigdelset},
    {"sigemptyset", (uintptr_t)&stub_sigemptyset},
    {"sigfillset", (uintptr_t)&stub_sigfillset},
    {"sigismember", (uintptr_t)&stub_sigismember},
    {"siglongjmp", (uintptr_t)&shim_siglongjmp},
    {"signal", (uintptr_t)&signal},
    {"sigpending", (uintptr_t)&stub_sigpending},
    {"sigprocmask", (uintptr_t)&stub_sigprocmask},
    {"sigtimedwait", (uintptr_t)&stub_sigtimedwait},
    {"sigwait", (uintptr_t)&stub_sigwait},
    {"sigwaitinfo", (uintptr_t)&stub_sigwaitinfo},
    {"sin", (uintptr_t)&sin},
    {"sincos", (uintptr_t)&sincos},
    {"sincosf", (uintptr_t)&sincosf},
    {"sinf", (uintptr_t)&sinf},
    {"sinh", (uintptr_t)&sinh},
    {"sinhf", (uintptr_t)&sinhf},
    {"sleep", (uintptr_t)&sleep},
    {"snprintf", (uintptr_t)&snprintf},
    {"socket", (uintptr_t)&net_socket},
    {"socketpair", (uintptr_t)&net_socketpair},
    {"splice", (uintptr_t)&stub_splice},
    {"sprintf", (uintptr_t)&sprintf},
    {"sqrt", (uintptr_t)&sqrt},
    {"srand", (uintptr_t)&srand},
    {"sscanf", (uintptr_t)&sscanf},
    {"stat", (uintptr_t)&bionic_stat},
    {"statfs", (uintptr_t)&bionic_statfs},
    {"statvfs", (uintptr_t)&bionic_statvfs},
    {"stderr", (uintptr_t)&bionic_stderr},
    {"stdin", (uintptr_t)&bionic_stdin},
    {"stdout", (uintptr_t)&bionic_stdout},
    {"strcat", (uintptr_t)&strcat},
    {"strchr", (uintptr_t)&strchr},
    {"strcmp", (uintptr_t)&strcmp},
    {"strcoll_l", (uintptr_t)&shim_strcoll_l},
    {"strcpy", (uintptr_t)&strcpy},
    {"strcspn", (uintptr_t)&strcspn},
    {"strdup", (uintptr_t)&strdup},
    {"strerror", (uintptr_t)&shim_strerror},
    {"strerror_r", (uintptr_t)&shim_strerror_r},
    {"strftime_l", (uintptr_t)&shim_strftime_l},
    {"strlen", (uintptr_t)&strlen},
    {"strncat", (uintptr_t)&strncat},
    {"strncmp", (uintptr_t)&strncmp},
    {"strncpy", (uintptr_t)&strncpy},
    {"strnlen", (uintptr_t)&strnlen},
    {"strpbrk", (uintptr_t)&strpbrk},
    {"strrchr", (uintptr_t)&strrchr},
    {"strsignal", (uintptr_t)&strsignal},
    {"strspn", (uintptr_t)&strspn},
    {"strstr", (uintptr_t)&strstr},
    {"strtod", (uintptr_t)&strtod},
    {"strtof", (uintptr_t)&strtof},
    {"strtok_r", (uintptr_t)&strtok_r},
    {"strtol", (uintptr_t)&strtol},
    {"strtold", (uintptr_t)&strtold},
    {"strtold_l", (uintptr_t)&shim_strtold_l},
    {"strtoll", (uintptr_t)&strtoll},
    {"strtoll_l", (uintptr_t)&shim_strtoll_l},
    {"strtoul", (uintptr_t)&strtoul},
    {"strtoull", (uintptr_t)&strtoull},
    {"strtoull_l", (uintptr_t)&shim_strtoull_l},
    {"strxfrm_l", (uintptr_t)&shim_strxfrm_l},
    {"swprintf", (uintptr_t)&swprintf},
    {"symlink", (uintptr_t)&stub_symlink},
    {"symlinkat", (uintptr_t)&stub_symlinkat},
    {"sync", (uintptr_t)&stub_sync},
    {"syscall", (uintptr_t)&bionic_syscall},
    {"sysconf", (uintptr_t)&bionic_sysconf},
    {"syslog", (uintptr_t)&stub_syslog},
    {"system", (uintptr_t)&stub_system},
    {"tan", (uintptr_t)&tan},
    {"tanf", (uintptr_t)&tanf},
    {"tanh", (uintptr_t)&tanh},
    {"tcgetpgrp", (uintptr_t)&stub_tcgetpgrp},
    {"tcsetpgrp", (uintptr_t)&stub_tcsetpgrp},
    {"time", (uintptr_t)&time},
    {"timerfd_create", (uintptr_t)&stub_timerfd_create},
    {"timerfd_gettime", (uintptr_t)&stub_timerfd_gettime},
    {"timerfd_settime", (uintptr_t)&stub_timerfd_settime},
    {"times", (uintptr_t)&times},
    {"towlower_l", (uintptr_t)&shim_towlower_l},
    {"towupper", (uintptr_t)&towupper},
    {"towupper_l", (uintptr_t)&shim_towupper_l},
    {"trunc", (uintptr_t)&trunc},
    {"truncate", (uintptr_t)&bionic_truncate},
    {"ttyname_r", (uintptr_t)&stub_ttyname_r},
    {"tzname", (uintptr_t)&bionic_tzname},
    {"umask", (uintptr_t)&stub_umask},
    {"uname", (uintptr_t)&shim_uname},
    {"ungetc", (uintptr_t)&shim_ungetc},
    {"ungetwc", (uintptr_t)&shim_ungetwc},
    {"unlink", (uintptr_t)&bionic_unlink},
    {"unlinkat", (uintptr_t)&bionic_unlinkat},
    {"unlockpt", (uintptr_t)&stub_unlockpt},
    {"unsetenv", (uintptr_t)&bionic_unsetenv},
    {"unshare", (uintptr_t)&stub_unshare},
    {"uselocale", (uintptr_t)&bionic_uselocale},
    {"usleep", (uintptr_t)&usleep},
    {"utimensat", (uintptr_t)&stub_utimensat},
    {"utimes", (uintptr_t)&stub_utimes},
    {"vasprintf", (uintptr_t)&vasprintf},
    {"vfork", (uintptr_t)&stub_vfork},
    {"vfprintf", (uintptr_t)&shim_vfprintf},
    {"vsnprintf", (uintptr_t)&vsnprintf},
    {"vsscanf", (uintptr_t)&vsscanf},
    {"wait", (uintptr_t)&stub_wait},
    {"wait4", (uintptr_t)&stub_wait4},
    {"waitid", (uintptr_t)&stub_waitid},
    {"waitpid", (uintptr_t)&stub_waitpid},
    {"wcrtomb", (uintptr_t)&wcrtomb},
    {"wcschr", (uintptr_t)&wcschr},
    {"wcscmp", (uintptr_t)&wcscmp},
    {"wcscoll", (uintptr_t)&wcscoll},
    {"wcscoll_l", (uintptr_t)&shim_wcscoll_l},
    {"wcscpy", (uintptr_t)&wcscpy},
    {"wcsftime", (uintptr_t)&wcsftime},
    {"wcslen", (uintptr_t)&wcslen},
    {"wcsncmp", (uintptr_t)&wcsncmp},
    {"wcsncpy", (uintptr_t)&wcsncpy},
    {"wcsnrtombs", (uintptr_t)&wcsnrtombs},
    {"wcsrchr", (uintptr_t)&wcsrchr},
    {"wcstod", (uintptr_t)&wcstod},
    {"wcstof", (uintptr_t)&wcstof},
    {"wcstok", (uintptr_t)&wcstok},
    {"wcstol", (uintptr_t)&wcstol},
    {"wcstold", (uintptr_t)&wcstold},
    {"wcstoll", (uintptr_t)&wcstoll},
    {"wcstombs", (uintptr_t)&wcstombs},
    {"wcstoul", (uintptr_t)&wcstoul},
    {"wcstoull", (uintptr_t)&wcstoull},
    {"wcsxfrm", (uintptr_t)&wcsxfrm},
    {"wcsxfrm_l", (uintptr_t)&shim_wcsxfrm_l},
    {"wctob", (uintptr_t)&wctob},
    {"wmemchr", (uintptr_t)&wmemchr},
    {"wmemcmp", (uintptr_t)&wmemcmp},
    {"write", (uintptr_t)&bionic_write},
    {"writev", (uintptr_t)&shim_writev},
    {"zlibVersion", (uintptr_t)&zlibVersion},
};

const size_t dynlib_function_count =
    sizeof dynlib_functions / sizeof dynlib_functions[0];

uintptr_t dynlib_find_export(const char *name) {
  if (!name) return 0;
  for (size_t i = 0; i < dynlib_function_count; i++)
    if (!strcmp(dynlib_functions[i].symbol, name)) return dynlib_functions[i].func;
  return 0;
}
